niveditaprity/Leetcode_Daily_Challenge

- November/Day4/reverseVowels.java
Day4 / 345. Reverse Vowels of a String
> Day4 / 345. Reverse Vowels of a String

- November/Day1/Where Will the Ball Fall.py
> Create Where Will the Ball Fall.py

- November/Day5/WordSearchII.java
> Day5 / WordSearchII

- November/Day4/Reverse Vowels of a String.py
Python solution Using Two Pointers
> Create Reverse Vowels of a String.py

- November/Day6/orderlyQueue.java
> Day6 / orderlyQueue

- November/Day6/orderly_queue.py
I want to contribute Python solutions for the daily challenges!
> add Python solution for day 6

- November/Day3/longestPalindrome.java
> Day3 / longestPalindrome

- November/Day8/make_the_string_great.py
added python solutions from brute force to optimal
> added python solutions

- November/Day8/makeStringGreat.java
>  Day8 / makeStringGreat

- November/Day10/removeAdjacentString.java
Day10 / removeAdjacentString.java
> Day10 / removeAdjacentString.java

- November/Day12/medianFromDataStream.java
> Day12 / medianFromDataStream

- November/Day17/rectangleArea.java
> Day17 / rectangleArea.java

- November/Day19/erectTheFence.java
> Day19 / erectTheFence.java

- November/Day30/unique_occurrences.py
- Q. https://leetcode.com/problems/unique-number-of-occurrences/ (Nov 30)
- Python solution
> unique occurrence python solution

- December/Day1/detemine_if_string_halves_are_alike.py
- Q. https://leetcode.com/problems/determine-if-string-halves-are-alike/ (Dec 1)
> determine if string halves are alike

- December/Day2/determine_if_two_strings_are_close.py
- Q. https://leetcode.com/problems/determine-if-two-strings-are-close/ (Dec 2)
> determine if two strings are close

- December/Day3/451_sort_character_by_frequency.py
- Q. https://leetcode.com/problems/sort-characters-by-frequency/ (Dec 3)
> Sort characters by frequency

- December/Day4/minimum-average-difference.cpp
- December/Day5/middle-of-the-linked-list.cpp
Codes for day 4 and day 5 of December leetcode challenge is added. Both the codes are optimized in terms of time and space. Space complexity and time complexity is added in the commit message.
> Added December Day-4 and Day-5 code.

- December/Day6/odd_even_linked_list.py
- Q. https://leetcode.com/problems/odd-even-linked-list/ (Dec 6)
> odd even linked list

- December/Day7/range-sum-of-bst.cpp
Added Leetcode December Day 7 challenge (Range Sum of BST ) code. The code runs with O(N) Time Complexity and takes O(N) Space Complexity (because of Recursive Stack).
> Leetcode December Challenge Day 7 code added.

- December/Day7/range_sum_of_bst.py
- Q. https://leetcode.com/problems/range-sum-of-bst/ (Dec 7)
> Range sum of bst

- December/Day11/binary-tree-maximum-path-sum.cpp
**Day 11 (Binary Tree Maximum Path Sum)** code of Decemeber Leetcode Challenge is added in this commit. The code runs in **O(N) Time Complexity** and takes **O(N) Recursive Stack Space**.
> Day 11 code of Decemeber Leetcode Challenge added. 

- December/Day13/minimum-falling-path-sum.cpp
Added the Day 13 code (931. **Minimum Falling Path Sum**) of December Leetcode Challenge. The problem is solved using **Bottom Up Dynamic Programming approach**. Space Complexity is improved by taking only **2 N sized DP arrays instead of using N*N DP matrix**. 
Time Complexity: O(N^2) 
Space Complexity: O(N). [Used 2 N sized arrays for previous Dp and current DP]
> Code for Day 13 of December Leetcode Challenge added

- December/Day18/daily_temperature.py
- Q. https://leetcode.com/problems/daily-temperatures/ (Dec 18)
> daily temperature

- December/Day27/jsSolution
Time Complexity is O(nlogn).
Space Complexity is O (1).
this solution beats Runtime by 92% & Memory Beats by 100%
> Added JS solution of Q 2279.
